/* Autogenerated by hxtools bin2c */
#ifndef CURLY_ICON_H
#define CURLY_ICON_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_curly_icon_png[3084];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* CURLY_ICON_H */
