/* Autogenerated by hxtools bin2c */
#ifndef CURLY_BMP_H
#define CURLY_BMP_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_curly_rdr_png[5045];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* CURLY_BMP_H */
